// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjeJAskKk2rwLmqSNXfXVQkZvuEbFZRPc',
    appId: '1:462413284970:web:257f78c40c4e35a31d6c13',
    messagingSenderId: '462413284970',
    projectId: 'flutter-app-d22d3',
    authDomain: 'flutter-app-d22d3.firebaseapp.com',
    storageBucket: 'flutter-app-d22d3.firebasestorage.app',
    measurementId: 'G-N4S8VNBWPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi5EaOxK2UEC43M1ZVMzD4k0yavdPugks',
    appId: '1:462413284970:android:732c61c0a6bd8e391d6c13',
    messagingSenderId: '462413284970',
    projectId: 'flutter-app-d22d3',
    storageBucket: 'flutter-app-d22d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu3oG5VE-jx0C37WUGv47oMVe4FwaJz1A',
    appId: '1:462413284970:ios:b38f798473b4bf381d6c13',
    messagingSenderId: '462413284970',
    projectId: 'flutter-app-d22d3',
    storageBucket: 'flutter-app-d22d3.firebasestorage.app',
    iosBundleId: 'com.example.flutterMedicamentos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu3oG5VE-jx0C37WUGv47oMVe4FwaJz1A',
    appId: '1:462413284970:ios:b38f798473b4bf381d6c13',
    messagingSenderId: '462413284970',
    projectId: 'flutter-app-d22d3',
    storageBucket: 'flutter-app-d22d3.firebasestorage.app',
    iosBundleId: 'com.example.flutterMedicamentos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjeJAskKk2rwLmqSNXfXVQkZvuEbFZRPc',
    appId: '1:462413284970:web:499c74223ef798701d6c13',
    messagingSenderId: '462413284970',
    projectId: 'flutter-app-d22d3',
    authDomain: 'flutter-app-d22d3.firebaseapp.com',
    storageBucket: 'flutter-app-d22d3.firebasestorage.app',
    measurementId: 'G-GRKT6G78F4',
  );
}
